// This file was autogenerated by ./js/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../ldc/datamodel/index.js', ['ldc.datamodel'], ['ldc.datamodel.Segment', 'ldc.datamodel.Table', 'ldc.datamodel.Update']);
goog.addDependency('../../../ldc/datamodel/segment.js', ['ldc.datamodel.Segment'], []);
goog.addDependency('../../../ldc/datamodel/segmentset.js', ['ldc.datamodel.SegmentSet'], []);
goog.addDependency('../../../ldc/datamodel/table.js', ['ldc.datamodel.Table'], ['ldc.datamodel.Update', 'ldc.event.DataUpdateEvent']);
goog.addDependency('../../../ldc/datamodel/update.js', ['ldc.datamodel.Update'], []);
goog.addDependency('../../../ldc/event/eventbus.js', ['ldc.event.EventBus'], []);
goog.addDependency('../../../ldc/event/events.js', ['ldc.event.DataUpdateEvent', 'ldc.event.Event'], []);
goog.addDependency('../../../ldc/event/index.js', ['ldc.event'], ['ldc.event.Event', 'ldc.event.EventBus']);
goog.addDependency('../../../ldc/index.js', ['ldc'], ['ldc.datamodel', 'ldc.event', 'ldc.textdisplay', 'ldc.waveform']);
goog.addDependency('../../../ldc/mediaplayer/audioplayer.js', ['ldc.mediaplayer.AudioPlayer'], []);
goog.addDependency('../../../ldc/mediaplayer/index.js', ['ldc.mediaplayer'], ['ldc.mediaplayer.AudioPlayer']);
goog.addDependency('../../../ldc/textdisplay/index.js', ['ldc.textdisplay'], ['ldc.textdisplay.SegmentEdit', 'ldc.textdisplay.TextEdit']);
goog.addDependency('../../../ldc/textdisplay/segmentedit.js', ['ldc.textdisplay.SegmentEdit'], ['goog.dom', 'ldc.datamodel.Update']);
goog.addDependency('../../../ldc/textdisplay/textedit.js', ['ldc.textdisplay.TextEdit'], ['goog.dom', 'goog.events', 'ldc.datamodel.Segment', 'ldc.event.Event', 'ldc.textdisplay.SegmentEdit']);
goog.addDependency('../../../ldc/waveform/index.js', ['ldc.waveform'], ['ldc.waveform.RichWaveform', 'ldc.waveform.Scrollbar', 'ldc.waveform.Waveform', 'ldc.waveform.WaveformBuffer', 'ldc.waveform.WaveformSet']);
goog.addDependency('../../../ldc/waveform/richwaveform.js', ['ldc.waveform.RichWaveform'], ['goog.dom', 'ldc.waveform.Waveform']);
goog.addDependency('../../../ldc/waveform/scrollbar.js', ['ldc.waveform.Scrollbar'], ['goog.cssom', 'goog.ui.Slider']);
goog.addDependency('../../../ldc/waveform/waveform.js', ['ldc.waveform.Waveform'], ['goog.array', 'goog.dom']);
goog.addDependency('../../../ldc/waveform/waveformbuffer.js', ['ldc.waveform.WaveformBuffer'], []);
goog.addDependency('../../../ldc/waveform/waveformset.js', ['ldc.waveform.WaveformSet'], []);
